name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Graph
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push to output branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update snake contribution graph"
          branch: output
